baseURL = "/"
languageCode = "pl-pl"
title = "Festiwal Światła 2024"
timeout = 600000
DefaultContentLanguage = "pl"

[module]
[module.hugoVersion]
extended = true
min = "0.128.0"

[[module.imports]]
path = 'github.com/DoomHammer/hugo-serif-theme'

[[module.imports]]
path = 'github.com/DoomHammer/hugo-shortcode-gallery'

theme = ["hugo-serif-theme", "hugo-shortcode-gallery"]

[[module.mounts]]
source = 'en/content/galeria'
target = 'en/content/galeria'
[[module.mounts]]
source = 'pl/content/galeria'
target = 'en/content/galeria'

[languages]
[languages.pl]
languageName = "🇵🇱"
contentDir = 'content/pl'

[languages.en]
title = "Festival of Light 2024"
contentDir = 'content/en'
languageName = "🇬🇧"

[params]
# In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
google_analytics_id = ""
google_tag_manager_id = ""
custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]

[params.homepage]
show_contact_box = true     # show / hide the contaxt box on the homepage
show_services_button = true # show / hide the "view all services" button

[params.logo]
mobile = "images/logo/newlogo.svg"
mobile_height = "36px"
desktop = "images/logo/newlogo.svg"
desktop_height = "36px"
alt = "Logo Festiwalu Światła - FŚ"

[params.fonts]
# sets the google font link in layouts/partials/google-fonts.html
google_fonts = 'https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap'
heading = "Poppins"
base = "Poppins"

[params.colors]

primary = "#956dfe"
black = "#000000"
white = "#ffffff"
white_offset = "#f6f7ff"
grey = "#8b8b8b"

[params.seo]
meta_twitter_site = "@hs3city"
meta_twitter_creator = "@hs3city"
meta_og_image = "https://festiwalswiatla.hs3.pl/images/program/program2022.png"

[params.team]
summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

[languages.pl.params.footer]
copyright_text = 'Dołącz do nas!'
copyright_link = '/kontakt'

[languages.en.params.footer]
copyright_text = 'Join us!'
copyright_link = '/kontakt'

[menu]
# Main Menu
[[menu.main]]
identifier = "about-us"
url = "/o-nas/"
weight = 5

[[menu.main]]
identifier = "gallery"
url = "/galeria/"
weight = 6

[[menu.main]]
identifier = "contact"
url = "/kontakt/"
weight = 7

[[menu.main]]
identifier = "program"
url = "/program/"
weight = 1

[[menu.main]]
identifier = "exhibitions"
url = "/wystawy/"
weight = 2

[[menu.main]]
identifier = "workshops"
url = "/warsztaty/"
weight = 2

[[menu.main]]
identifier = "shows"
url = "/pokazy/"
weight = 3

[[menu.main]]
identifier = "artists"
url = "/artysci/"
weight = 4

[[menu.main]]
identifier = "previous-editions"
url = "/poprzednie-edycje/"
weight = 8

# Footer Menu
[[menu.footer]]
identifier = "contact"
url = "/kontakt/"
weight = 2

[[menu.footer]]
identifier = "homepage"
url = "/"
weight = 1

[[menu.footer]]
name = "Hackerspace Trójmiasto"
url = "https://hs3.pl"
weight = 3

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.image]
enableDefault = true
