[build]
publish = "public"
command = "npm i -D postcss postcss-cli  @fullhuman/postcss-purgecss; hugo --minify;"

[build.environment]
HUGO_VERSION = "0.128.1"

[context.deploy-preview]
command = "npm i -D postcss postcss-cli  @fullhuman/postcss-purgecss; hugo --minify -b $DEPLOY_PRIME_URL;"
