[build]
publish = "public"
command = "hugo version; hugo mod get; hugo --minify;"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = "hugo version; hugo mod get; hugo --minify -b $DEPLOY_PRIME_URL;"
