[build]
publish = "public"
command = "hugo version; hugo mod get; hugo --minify --baseURL $DEPLOY_PRIME_URL;"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = "hugo version; hugo mod get; hugo --minify --baseURL $DEPLOY_PRIME_URL;"
